name: pbl5
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.2
  firebase_analytics: ^10.1.3
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  flow_builder: ^0.0.9
  multiple_result: ^4.0.0
  formz: ^0.5.0+1
  go_router: ^6.2.0
flutter:
  uses-material-design: true
